language: node_js
node_js:
  - node
jobs:
  include:
    - stage: test
      script: 
        - npm install -g codecov
        - yarn install --pure-lockfile
        - yarn build
        - yarn test
        - yarn coverage
        - codecov
        - yarn prettier
    - stage: deploy
      script:
        - yarn install --pure-lockfile
        - yarn build
        - bash scripts/deploy.sh
stages:
  - name: test
    if: (type = pull_request) OR ((type = push) AND (branch = master))
  - name: deploy
    if: branch = master
